from unittest import TestCase

from repeated_string_match import Solution

s = Solution()


class TestSolution(TestCase):
    """"""

    def test_0(self):
        self.assertEqual(s.repeatedStringMatch("abcd", "cdabcdab"), 3)

    def test_1(self):
        self.assertEqual(s.repeatedStringMatch("abcde", "cdabcdab"), -1)

    def test_2(self):
        self.assertEqual(s.repeatedStringMatch("abcabcabcabc", "abac"), -1)

    def test_3(self):
        self.assertEqual(s.repeatedStringMatch("cccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccab", "ccccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabccccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabccccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabbcccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabccccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabacccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabbcccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabbcccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabccccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabbcccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabbcccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabbcccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabbcccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabbcccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabccccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabbcccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabacccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabccccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabacccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabacccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabacccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabbcccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabbcccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabccccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabbcccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabacccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabacccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabacccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabbcccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabacccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabacccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabccccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabbcccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabacccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabacccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabbcccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabbcccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabbcccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabccccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabccccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabacccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabacccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabccccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabbcccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabbcccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabbcccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabccccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabccccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabacccbcabbcbbbbbcbacaaabbcbaaabaacbaabbbccaacbbbccabb"), -1)

    def test_4(self):
        self.assertEqual(s.repeatedStringMatch("a", "aa"), 2)
